services:
  backend:
    image: api_pathfinding
    container_name: api_pathfinding
    build: .
    attach: false
    restart: always
    #networks:
    # - edgeb-network
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000

networks:
  edgeb-network:
    external: true
